#!/usr/bin/env bash

########################
# install dependencies #
########################

command -v mysqldump &>/dev/null || {
  command -v apt-get &>/dev/null && {
    sudo apt-get update
    sudo apt-get install -y -qq mysql-client
  }
}

command -v mysql &>/dev/null || {
  command -v apt-get &>/dev/null && {
    sudo apt-get update
    sudo apt-get install -y -qq mysql-client
  }
}

############################
# Fetch required variables #
############################

# Fetch source server
if [[ ! $SRC_SERVER ]] ; then
  echo -n "Enter source server [localhost]: "
  read SRC_SERVER
  [[ -z "$SRC_SERVER" ]] && SRC_SERVER=localhost
fi

# Fetch source user
if [[ ! $SRC_USER ]] ; then
  echo -n "Enter source user [admin]: "
  read SRC_USER
  [[ -z "$SRC_USER" ]] && SRC_USER=admin
fi

# Fetch source password
if [[ ! $SRC_PASS ]] ; then
  echo -n "Enter source password: "
  read -s SRC_PASS
  [[ -z "$SRC_PASS" ]] && SRC_PASS=
  echo ""
fi

###################################
# Check what we're supposed to do #
###################################

case "$1" in

  list) # list databases on the server
    echo "SHOW DATABASES;" | mysql -h "${SRC_SERVER}" -u "${SRC_USER}" "--password=${SRC_PASS}" "${SRC_DB}" 2>/dev/null | tail -n +2
    ;;

  tables) # list tables in the database

    # Fetch source database
    if [[ ! $SRC_DB ]] ; then
      echo -n "Enter source database [trackthis]: "
      read SRC_DB
      [[ -z "$SRC_DB" ]] && SRC_DB=trackthis
    fi

    echo "SHOW TABLES;" | mysql -h "${SRC_SERVER}" -u "${SRC_USER}" "--password=${SRC_PASS}" "${SRC_DB}" 2>/dev/null | tail -n +2
    ;;

  copy-table) # copy a single table

    # Fetch source database
    if [[ ! $SRC_DB ]] ; then
      echo -n "Enter source database [trackthis]: "
      read SRC_DB
      [[ -z "$SRC_DB" ]] && SRC_DB=trackthis
    fi

    # Fetch source table
    if [[ ! $SRC_TABLE ]] ; then

      if [[ $2 ]] ; then
        SRC_TABLE=$2
      else
        echo -n "Enter source table: "
        read SRC_TABLE
        [[ -z "$SRC_TABLE" ]] && SRC_TABLE=trackthis
      fi
    fi

    # Fetch target server
    if [[ ! $TGT_SERVER ]] ; then
      echo -n "Enter target server [localhost]: "
      read TGT_SERVER
      [[ -z "$TGT_SERVER" ]] && TGT_SERVER=localhost
    fi

    # Fetch target user
    if [[ ! $TGT_USER ]] ; then
      echo -n "Enter target user [admin]: "
      read TGT_USER
      [[ -z "$TGT_USER" ]] && TGT_USER=admin
    fi

    # Fetch target password
    if [[ ! $TGT_PASS ]] ; then
      echo -n "Enter target password: "
      read -s TGT_PASS
      [[ -z "$TGT_PASS" ]] && TGT_PASS=
      echo ""
    fi

    # Fetch target database
    if [[ ! $TGT_DB ]] ; then
      echo -n "Enter target database [trackthis]: "
      read TGT_DB
      [[ -z "$TGT_DB" ]] && TGT_DB=trackthis
    fi

    # Actually copy the thing
    # --no-create-db
    # --skip-add-drop-table
    mysqldump -C -h "${SRC_SERVER}" -u "${SRC_USER}" "--password=${SRC_PASS}" "${SRC_DB}" "${SRC_TABLE}" --quick --skip-triggers --insert-ignore --skip-lock-tables | pv |\
      sed 's/CREATE TABLE/CREATE TABLE IF NOT EXISTS/' |\
      mysql -C -h "${TGT_SERVER}" -u "${TGT_USER}" "--password=${TGT_PASS}" "${TGT_DB}" 2>&1 | grep -v "[Warning] Using a password"

    ;;

  copy-all-tables)

    # Fetch source database
    if [[ ! $SRC_DB ]] ; then
      echo -n "Enter source database [trackthis]: "
      read SRC_DB
      [[ -z "$SRC_DB" ]] && SRC_DB=trackthis
    fi

    # Fetch target server
    if [[ ! $TGT_SERVER ]] ; then
      echo -n "Enter target server [localhost]: "
      read TGT_SERVER
      [[ -z "$TGT_SERVER" ]] && TGT_SERVER=localhost
    fi

    # Fetch target user
    if [[ ! $TGT_USER ]] ; then
      echo -n "Enter target user [admin]: "
      read TGT_USER
      [[ -z "$TGT_USER" ]] && TGT_USER=admin
    fi

    # Fetch target password
    if [[ ! $TGT_PASS ]] ; then
      echo -n "Enter target password: "
      read -s TGT_PASS
      [[ -z "$TGT_PASS" ]] && TGT_PASS=
      echo ""
    fi

    # Fetch target database
    if [[ ! $TGT_DB ]] ; then
      echo -n "Enter target database [trackthis]: "
      read TGT_DB
      [[ -z "$TGT_DB" ]] && TGT_DB=trackthis
    fi

    # Fetch tables
    export SRC_SERVER
    export SRC_USER
    export SRC_PASS
    export SRC_DB
    TABLES=$($0 tables)

    # Export targets for child processes
    export TGT_SERVER
    export TGT_USER
    export TGT_PASS
    export TGT_DB

    # Copy table-for-table
    echo $TABLES | tr ' ' '\n' | parallel -j2 $0 copy-table {}

    ;;
esac
