#!/usr/bin/env bash

# We're done
if [ -z "$1" ]; then
    exit 0
fi

# Detect package manager & let the packages handle it further

# Try apt-get
command -v apt-get &>/dev/null && {
  sudo apt-get install -y -qq $( cat ../config/packages/apt-get/$1 )
  exec $0 "${@:2}"
}

# Try xbps
command -v xbps-install &>/dev/null && {
  sudo xbps-install -Suvy $( cat ../config/packages/xbps/$1 )
  exec $0 "${@:2}"
}
